### PR TITLE
start status worker with transport

### PR DESCRIPTION
**Pull request by rudigiesler**

### CODE REVIEW

**Comment by rudigiesler** [comment]
This PR requires #44 to land and merge before it will make sense

**Comment by rudigiesler** [comment]
Ready for review.

**Comment by justinvdm** [comment]
:+1:

We still need to change the config we give to the transport to set `publish_status` to `True`. Not sure if that is something we want to do in this PR or a separate PR.

**Comment by rudigiesler** [comment]
I think I'll do it in this PR, it seems related

**Comment by rudigiesler** [comment]
Ready for review again

**Comment by justinvdm** [comment]
:+1:

**Pull request merged**
