### PR TITLE
Fix config file loading

### PR DESCRIPTION
**Pull request by rudigiesler**

### CODE REVIEW

**Comment by rudigiesler** [comment]
This was a bug that I found when making the dockerfile. `yaml.safe_load` expects a file, not a filename. Ready for review.

**Comment by rudigiesler** [comment]
Travis failure is because of new twisted version not supporting Python 2.6. I can't remember what we decided to do. Not support Python 2.6, or switch to an older version of twisted for 2.6?

**Comment by hodgestar** [comment]
Looks good. Do we have a test for `load_config(None)`?

**Comment by rudigiesler** [comment]
Test added for `load_config(None)`

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
