### PR TITLE
Add /s for collection api endpoints

### PR DESCRIPTION
**Pull request by justinvdm**
To be more RESTful, it would be nice to have collection api endpoints that look like `/channels/` instead of `/channels`.

### CODE REVIEW

**Comment by justinvdm** [comment]
Ready for review.

**Comment by rudigiesler** [comment]
Maybe we should do the same for `/channels/channel-id/messages` to be consistent?

**Comment by justinvdm** [comment]
Thanks, missed that :)

**Comment by justinvdm** [comment]
Done.

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
